name: Flutter CI

on:
  pull_request:
    branches:
      - main

jobs:
  format-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Flutter 3.3.10
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'
          channel: 'stable'
          cache: 'true'
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path:
          ${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:
      - name: Run Flutter Format
        run: flutter format lib
      - name: Checkout Formatted Files
        run: git checkout -- .
      # Check if there are any changes to commit
      - name: Check for Changes
        run: |
          CHANGES_TO_COMMIT=$(git diff-index --quiet HEAD || echo "true")
      # Commit formatted files
      - name: Commit Formatted Files
        run: git config --local user.email "action@github.com" && git config --local user.name "GitHub Action" && git commit -am "Format code"
        # Skip this step if there are no changes
        if: ${{CHANGES_TO_COMMIT != '' }}
      - name: Push Formatted Changes
        run: git push origin HEAD:${{ github.head_ref }}
      - name: Run Flutter Analyze
        run: flutter analyze
      - name: Check for Issues
        if: ${{ steps.analyze.outputs.exit-code != 0}}
        run: exit 1
